version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_github_2003Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: ISRepoUnderProject
  gitServerName: RAHS_Azure_Account
  gitUrl: https://dev.azure.com/rahs/AzureRepoWorkProject/_git
  gitUsername: rahs
  gitBranch: master
